### ISSUE TITLE
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

### ISSUE THREAD

**Issue by tinomhishi** [django-helpdesk/django-helpdesk#621]
Getting above error after creating new ticket. What might be the issue.

**Comment by tinomhishi** [comment]
Have looking all over. Can not find a solution.

**Comment by gwasser** [comment]
According to [this page](https://bugs.python.org/issue27682) it's not clear if this error is an error in the Python standard libraries or Django. Either way, I don't think this is because of `django-helpdesk`. I would recommend ensuring you're using the latest version of both Python and Django. Also sounds like you're using Windows? You might have better success on a Linux host.

**Comment by tinomhishi** [comment]
@gwasser thanks for responding. I did as you said. Tried deploying on a Linux host but mail still not being sent out.

**Comment by gwasser** [comment]
Do you get the same error message or is it different?

**Comment by tinomhishi** [comment]
Sorry for leaving out that detail. The error is gone but the emails are still not going out

**Comment by tinomhishi** [comment]
Please close this issue. I think it was a python bug as @gwasser  said earlier. When I updated to the latest python it was fixed but I had not properly configured my settings that's why i didn't immediately see the problem was gone. Many thanks.

**Comment by gwasser** [comment]
Great! Glad it was fixed.

**Comment by thesunlover** [comment]
I got the same error on Python3.6 with django2.2 on my localhost

**Comment by gwasser** [comment]
Thanks, will take a look at that NoneType error at the end.

**Comment by cobianic** [comment]
Same problem, Windows 10, Python 3.6, Django 2.1.7, without virtualenv. Site works, but I am receiving these errors in the console

```
Exception happened during processing of request from ('192.168.0.104', 54480)
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\wsgiref\handlers.py", line 138, in run
    self.finish_response()
  File "C:\Program Files\Python36\lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "C:\Program Files\Python36\lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "C:\Program Files\Python36\lib\wsgiref\handlers.py", line 332, in send_headers
    self.send_preamble()
  File "C:\Program Files\Python36\lib\wsgiref\handlers.py", line 255, in send_preamble
    ('Date: %s\r\n' % format_date_time(time.time())).encode('iso-8859-1')
  File "C:\Program Files\Python36\lib\wsgiref\handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "C:\Program Files\Python36\lib\socketserver.py", line 800, in write
    self._sock.sendall(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\wsgiref\handlers.py", line 141, in run
    self.handle_error()
  File "C:\Program Files\Python36\lib\site-packages\django\core\servers\basehttp.py", line 116, in handle_error
    super().handle_error()
  File "C:\Program Files\Python36\lib\wsgiref\handlers.py", line 368, in handle_error
    self.finish_response()
  File "C:\Program Files\Python36\lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "C:\Program Files\Python36\lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "C:\Program Files\Python36\lib\wsgiref\handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "C:\Program Files\Python36\lib\wsgiref\handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\socketserver.py", line 651, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Program Files\Python36\lib\socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Program Files\Python36\lib\socketserver.py", line 721, in __init__
    self.handle()
  File "C:\Program Files\Python36\lib\site-packages\django\core\servers\basehttp.py", line 171, in handle
    self.handle_one_request()
  File "C:\Program Files\Python36\lib\site-packages\django\core\servers\basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
  File "C:\Program Files\Python36\lib\wsgiref\handlers.py", line 144, in run
    self.close()
  File "C:\Program Files\Python36\lib\site-packages\django\core\servers\basehttp.py", line 111, in close
    super().close()
  File "C:\Program Files\Python36\lib\wsgiref\simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by gwasser** [comment]
Thanks! I'm glad it does work and just gives console errors. I haven't used or tested this much from Windows. The error code suggests some kind of Windows error in the libraries and not django-helpdesk itself, but if there's some we can do to help mitigate, glad to merge that in.

In the meantime, if possible, can you run on linux to avoid the issue?

**Comment by thesunlover** [comment]
I remember that I got the error if I don't wait for the full load of the page, or even before it loads and I quit the browser tab. I need to correct the information I provided. My django version is also 2.1.7

**Comment by daB0bby** [comment]
This is a Python bug [here](https://bugs.python.org/issue27682) and should be fixed with python/cpython#9713

**Comment by gwasser** [comment]
Thanks! Looks like this issue will be fixed in the next Python 3.7 bugfix release, and 3.8 when it comes out.

**Comment by gwasser** [comment]
I'm marking this as documentation to remind myself that we should add a note to the docs that if you are using windows, we recommend Python 3.7+ to avoid this issue.

**Comment by lincal2309** [comment]
Hi all,
I used to have the same issue since a while.
I just updated to Python 3.7.3 (from 3.7.0), I use Django 2.2 and run pipenv virtual env on Windows 10 and I still have the issue (same message as the latest one posted).
As described above, everything works fine for my project and it's "only" warning message in the console (but it makes difficult to read print() messages ^^).
I read here and there this could come either from a database lock or a matter of files' size. I did my best to commit each db action (I use SQLite) and the only file I use in my latest project is 40kb so it should not be a big deal.
Thanks in advance for taking care of this.

**Comment by gwasser** [comment]
Thanks @lincal2309 for testing. To be clear, the bug report linked above suggested it won't be until the next bug release (Python 3.7.4, or later -- definitely scheduled as part of 3.8). We'll re-evaluate when it comes out if there's anything we can do on our end, hopefully it will be fixed!

**Comment by DBoyara** [comment]
I have same problem when antivirus is off. Python 3.7.2, Django 2.2.1, Win10 x64, Antivirus: Kaspersky Internet Security. When antivirus is enabled, everything works without this error "**ConnectionAbortedError: [WinError 10053]**".

**Comment by KANE-99** [comment]
Constantly getting this error **only on google chrome(works completely fine on FIrefox,Edge)**....
Exception happened during processing of request from ('127.0.0.1', 50106)
Traceback (most recent call last):
  File "C:\Users\kane\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\kane\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\kane\AppData\Local\Programs\Python\Python37-32\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\Users\kane\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\core\servers\basehttp.py", line 171, in handle
    self.handle_one_request()
  File "C:\Users\kane\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\core\servers\basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "C:\Users\kane\AppData\Local\Programs\Python\Python37-32\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
**I upgraded from 3.7.1 to 3.7.4 that got rid of the 'NoneType' errors but This ConnectionAbortedError still remains**

**Comment by gwasser** [comment]
Very strange, I wouldn't think the browser would have anything to do with this. Hmm. Thanks for the report! Hopefully we can narrow down a workaround. I unfortunately haven't had much time lately to look into it, so appreciate help from anyone reading this! Thanks.

**Comment by seenureddy** [comment]
Running the Python 3.7.4. Issue is exits 
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 58090)
Traceback (most recent call last):
  File "c:\program files\python37\Lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "c:\program files\python37\Lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "c:\program files\python37\Lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\lib\site-packages\django\core\servers\basehttp.py", line 171, in handle
    self.handle_one_request()
  File "C:\lib\site-packages\django\core\servers\basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "c:\program files\python37\Lib\socket.py", line 589, in readinto

**Comment by boshng95** [comment]
The upgrade from Python 3.7.3 to 3.7.4 remove the error message of AttributeError & TypeError. However, there is still one error message unable to resolve.

For my case, I had upgraded my Python to 3.7.4 & Django 2.2.4 with Windows 10 & run the server using Firefox Developer Edition. Still having an error as shown below:

ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

**Comment by gwasser** [comment]
The original bug thread seems to have a few reports of issues with 3.7.4. I'm not sure there's anything we can do here in `django-helpdesk`, it's an upstream bug. Hopefully will get a full fix in 3.8. A workaround might be coming in Django. https://bugs.python.org/issue27682

**Comment by inovizz** [comment]
> Please close this issue. I think it was a python bug as @gwasser said earlier. When I updated to the latest python it was fixed but I had not properly configured my settings that's why i didn't immediately see the problem was gone. Many thanks.

I'm facing the same issue. Which version of Python and Django you were using to make it work.

I'm on Python 3.6.4 and Django 2.2.4.

Kindly advise.

**Comment by gwasser** [comment]
Hi @inovizz please first try out Python 3.7 latest release and see if it helps.

**Comment by nicomech** [comment]
I am having the issue with django 2.2.1 & python 3.7.4.

Is there a plan to fix this in django (the bug in python is closed, without solving the issue in django...) ?

Thanks.

**Comment by gwasser** [comment]
Have you tried the latest Django release @nicomech? 2.2.6 is the latest. The bug report seemed to indicate they added a bugfix if I remember correctly, but maybe it was after 2.2.1. If it still causes an issue even when using 2.2.6, you might want to open a ticket with Django itself. I don't work on the Django core. We can also consider a workaround in django-helpdesk if that's possible, but I don't use Windows and so am not sure how to workaround it properly -- glad to take PRs if anyone else has an idea!

**Comment by nicomech** [comment]
I did tried with django 2.2.6 and had the same issue...

**Comment by jhtobav** [comment]
Hi everyone,

I'm getting the same error, my project is working fine but sometimes I get that error.

My versions:
Python 3.8.0
Django==2.2.7
Windows 10

### Error:

`Exception happened during processing of request from ('127.0.0.1', 54900)
Traceback (most recent call last):
  File "C:\Users\jhtob\AppData\Local\Programs\Python\Python38-32\Lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\jhtob\AppData\Local\Programs\Python\Python38-32\Lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\jhtob\AppData\Local\Programs\Python\Python38-32\Lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\Users\jhtob\Documents\codeProjects\nichtVergessen\mainModule\env\lib\site-packages\django\core\servers\basehttp.py", line 171, in handle
    self.handle_one_request()
  File "C:\Users\jhtob\Documents\codeProjects\nichtVergessen\mainModule\env\lib\site-packages\django\core\servers\basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "C:\Users\jhtob\AppData\Local\Programs\Python\Python38-32\Lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine`

**Comment by gwasser** [comment]
Thank you for the report! I'm disappointed that the latest python and django releases don't seem to address this error, so we need to figure out a good workaround. The traceback shows that it is all django/python code, not from django-helpdesk specifically, so I'm not sure the best way to handle it. Suggestions and pull requests welcome!

**Comment by maslanturk** [comment]
I'm having the same problem.

Python : 3.5.2
Django : 2.2.7
Windows : 10

Is there any solution?

**Comment by Domin19901111** [comment]
I'd like to track the latest ticket related to this issue but I can not find it. Can anybody linked it?
By the way I am using Python 3.7.4 and Django 2.2.7 on win10.

**Comment by gwasser** [comment]
Possibly related is #783.

**Comment by Joe-Khoa** [comment]
> 
> 
> Hi everyone,
> 
> I'm getting the same error, my project is working fine but sometimes I get that error.
> 
> My versions:
> Python 3.8.0
> Django==2.2.7
> Windows 10
> ### Error:
> 
> `Exception happened during processing of request from ('127.0.0.1', 54900) Traceback (most recent call last): File "C:\Users\jhtob\AppData\Local\Programs\Python\Python38-32\Lib\socketserver.py", line 650, in process_request_thread self.finish_request(request, client_address) File "C:\Users\jhtob\AppData\Local\Programs\Python\Python38-32\Lib\socketserver.py", line 360, in finish_request self.RequestHandlerClass(request, client_address, self) File "C:\Users\jhtob\AppData\Local\Programs\Python\Python38-32\Lib\socketserver.py", line 720, in __init__ self.handle() File "C:\Users\jhtob\Documents\codeProjects\nichtVergessen\mainModule\env\lib\site-packages\django\core\servers\basehttp.py", line 171, in handle self.handle_one_request() File "C:\Users\jhtob\Documents\codeProjects\nichtVergessen\mainModule\env\lib\site-packages\django\core\servers\basehttp.py", line 179, in handle_one_request self.raw_requestline = self.rfile.readline(65537) File "C:\Users\jhtob\AppData\Local\Programs\Python\Python38-32\Lib\socket.py", line 669, in readinto return self._sock.recv_into(b) ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine`

SAME TO MY VERSION

**Comment by gwasser** [comment]
Thanks for sharing! All the reading I've done so far pointed to this being a bug in python on windows, so I'm not sure if it still hasn't been fixed or if there's something we should be doing in `django-helpdesk`. If anyone has ideas, please let me know or submit a pull request!

I don't use Windows and so unfortunately I can't even test this.

**Comment by Joe-Khoa** [comment]
I'm using window. I re-install django-with-python-3.5 ( and then try 3.8 also OK) indepently with django.
NOT use " conda create --name myEnv django " .  BUT use : conda create --name myENV python=3.5 -> activate myENV ->  conda install django. So, i try and don't get this error anymore.

**Comment by sivexx** [comment]
had the same error on Win10 today although it was related to pure django and not django-helpdesk. It turned out Windows Defender was the one messing around - when I disabled it everything was ok, so after re-enabling it I've added port 8000 to allowed rules for both incoming and outgoing traffic and everything seems fine now.
Try it, maybe it will help your case.

**Comment by qwe99254** [comment]
This error(10053) in python scripts appears when I turn off my antivirus in Windows7.

**Comment by rafaelurben** [comment]
I got the same error (`ConnectionAbortedError: [WinError 10053]`) on Windows 10 without django-helpdesk (just a django project), so it might be a issue related to django or Python itself. PS: I only get this issue when I open the website in Firefox (also tested with Chrome) - I hope this helps.

**Comment by auphofBSF** [comment]
> I got the same error (`ConnectionAbortedError: [WinError 10053]`) on Windows 10 without django-helpdesk (just a django project), so it might be a issue related to django or Python itself. PS: I only get this issue when I open the website in Firefox (also tested with Chrome) - I hope this helps.

Same here, Python 3.7.6 Django 3.0.4 Win10 64 bit FIrefox 73.0.1 (64-bit) produces WinError 10053 but works fine on Chrome Version 80.0.3987.132 (Official Build) (64-bit).  This testing on a very basic example https://github.com/realpython/materials/tree/86c5009b84ef207c6dd1873ec9dc25afbe725347/rp-portfolio

**Comment by duri0214** [comment]
I got the same error.
I reached the python issue at github.

Python 3.7.2
Django==2.1.10
Win10 64bit
chrome 80.0.3987.132 (Official Build 64 bit）

this application is google map api playground using javascript and django.
windows only!?

>[15/Mar/2020 22:56:43] "POST /gmarker/search/1A HTTP/1.1" 302 0
Traceback (most recent call last):
  File "C:\Python\lib\wsgiref\handlers.py", line 138, in run
    self.finish_response()
  File "C:\Python\lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "C:\Python\lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "C:\Python\lib\wsgiref\handlers.py", line 332, in send_headers
    self.send_preamble()
  File "C:\Python\lib\wsgiref\handlers.py", line 255, in send_preamble
    ('Date: %s\r\n' % format_date_time(time.time())).encode('iso-8859-1')
  File "C:\Python\lib\wsgiref\handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "C:\Python\lib\socketserver.py", line 799, in write
    self._sock.sendall(b)
ConnectionAbortedError: [WinError 10053] 確立された接続がホスト コンピューターのソウトウェアによって中止されま 
した。
[15/Mar/2020 22:56:43] "POST /gmarker/search/1A HTTP/1.1" 500 59
>
>Exception happened during processing of request from ('127.0.0.1', 50135)
Traceback (most recent call last):
  File "C:\Python\lib\wsgiref\handlers.py", line 138, in run
    self.finish_response()
  File "C:\Python\lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "C:\Python\lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "C:\Python\lib\wsgiref\handlers.py", line 332, in send_headers
    self.send_preamble()
  File "C:\Python\lib\wsgiref\handlers.py", line 255, in send_preamble
    ('Date: %s\r\n' % format_date_time(time.time())).encode('iso-8859-1')
  File "C:\Python\lib\wsgiref\handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "C:\Python\lib\socketserver.py", line 799, in write
    self._sock.sendall(b)
ConnectionAbortedError: [WinError 10053] 確立された接続がホスト コンピューターのソウトウェアによって中止されま 
した。
>
>During handling of the above exception, another exception occurred:
>
>Traceback (most recent call last):
  File "C:\Python\lib\wsgiref\handlers.py", line 141, in run
    self.handle_error()
  File "C:\Python\lib\site-packages\django\core\servers\basehttp.py", line 116, in handle_error
    super().handle_error()
  File "C:\Python\lib\wsgiref\handlers.py", line 368, in handle_error
    self.finish_response()
  File "C:\Python\lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "C:\Python\lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "C:\Python\lib\wsgiref\handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "C:\Python\lib\wsgiref\handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable
>
>During handling of the above exception, another exception occurred:
>
>Traceback (most recent call last):
  File "C:\Python\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Python\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Python\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\Python\lib\site-packages\django\core\servers\basehttp.py", line 171, in handle
    self.handle_one_request()
  File "C:\Python\lib\site-packages\django\core\servers\basehttp.py", line 194, in handle_one_request
    handler.run(self.server.get_app())
  File "C:\Python\lib\wsgiref\handlers.py", line 144, in run
    self.close()
  File "C:\Python\lib\site-packages\django\core\servers\basehttp.py", line 111, in close
    super().close()
  File "C:\Python\lib\wsgiref\simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
>
>[15/Mar/2020 22:56:44] "POST /gmarker/search/1B HTTP/1.1" 302 0

**Comment by p4l4s6** [comment]
Python: 3.8.1
Django: 2.2.10
While using django-notification-hq I got the same error.
```
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 52716)
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Program Files\Python38\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Program Files\Python38\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "F:\ENGLISH\2020\Personal\Web\PointOfSale\venv\lib\site-packages\django\core\servers\basehttp.py", line 171, in handle
    self.handle_one_request()
  File "F:\ENGLISH\2020\Personal\Web\PointOfSale\venv\lib\site-packages\django\core\servers\basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "C:\Program Files\Python38\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
----------------------------------------
```

**Comment by KongKingo** [comment]
Windows 10, version 1909 DK
Python 3.8.2
Django 3.0.4.
Tutorial chapter 1/ https://docs.djangoproject.com/en/3.0/intro/tutorial01/
1st run with: >python manage.py runserver ==> loading localhost:8000 in FireFox returns:
>>The install worked successfully! Congratulations!
You are seeing this page because DEBUG=True is in your settings file and you have not configured any URLs.<< 
So that part of the turorial is fine.
In ther server console I receive similar mesages as previous users above:
Watching for file changes with StatReloader
Performing system checks...
System check identified no issues (0 silenced).
....
Quit the server with CTRL-BREAK.
[06/Apr/2020 14:37:55] "GET / HTTP/1.1" 200 16351
[06/Apr/2020 14:37:55] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
Not Found: /favicon.ico
[06/Apr/2020 14:37:55] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
Exception happened during processing of request from ('127.0.0.1', 14359)
[06/Apr/2020 14:37:55] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
Traceback (most recent call last):
[06/Apr/2020 14:37:55] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
  File "C:\Users\jb\AppData\Local\Programs\Python\Python38-32\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\jb\AppData\Local\Programs\Python\Python38-32\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\jb\AppData\Local\Programs\Python\Python38-32\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\Users\jb\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\servers\basehttp.py", line 174, in handle
    self.handle_one_request()
  File "C:\Users\jb\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\servers\basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "C:\Users\jb\AppData\Local\Programs\Python\Python38-32\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
ConnectionAbortedError: [WinError 10053] En oprettet forbindelse blev afbrudt af softwaren på værtscomputeren (=An established connection was aborted by the software in your host machine)

Any news?

**Comment by caot** [comment]
The issue has been around ten year or more, however I couldn't understand it.

**Comment by gwasser** [comment]
Yeah I admit I don't really understand what is going on, and this is only a problem on Windows which I don't use. I'm happy to merge in a patch but I simply don't know what to do about it. Other posts online suggested the issue was in Python libraries themselves, but so far don't seem fixed even as of the latest release (3.8).

**Comment by timthelion** [comment]
Probably the best solution would be to make sure we have a working
Dockerfile and tell people to use docker on windows. Developing server
side software on windows is a bit like tying a cannon to a row-boat and
trying to do naval drills with it anyways.

Question for the submitters. Are you trying to run django-helpdesk in
production on windows or simply develop on windows?

**Comment by samrose** [comment]
I am seeing this problem in a docker envrionment

Django version 2.2.12
python3.8
docker is based `FROM python:3`
Host machine is ubuntu


seeing 

```
Exception happened during processing of request from ('172.17.0.1', 54846)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/lib/python3.8/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.8/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
```

**Comment by samrose** [comment]
other mentions of this kind of issue elsewhere

https://www.reddit.com/r/django/comments/cv7sx7/exception_happend_during_processing_of_request/ 

https://stackoverflow.com/questions/57261024/python-django-errno-54-connection-reset-by-peer

**Comment by zed1025** [comment]
Since the issue is till open, I'd like to add an update
Python 3.7.7 (virtualenv)
Django 3.0.1
Windows

Still getting the error. The django site seems to work correctly, but my command prompt is a mess. Very hard to read anything.
I've tried the fix from the link by @samrose but it doesn't work.

**Comment by RanjithNagaraj** [comment]
I am also getting the same error
My python version is :3.7.3
Django :2.2.6

**Comment by amandeep1991** [comment]
Me too getting same issue. I am also running on Windows 10

**Comment by ducth1903** [comment]
I see the same issue as of June 2020
- Python 3.7.4
- Django 3.0.7
- Windows 10
- Firefox browser only (works fine on Chrome)

**Comment by gwasser** [comment]
Interesting, only get an error in Firefox? I have no idea what would make this browser dependent.

**Comment by NathanSalez** [comment]
Same for me in Windows 10 with Python 3.8.3 and Django 3.0.7 in localhost, I got the issue on Firefox and it works perfectly on Chrome.

**Comment by svhenrique** [comment]
Same problem for me in Windows 10 with python 3.8.5 and Django 3.0.8 in localhost. The issue only appears in Firefox but works perfectly on Microsoft Edge and Google Chrome

**Comment by gwasser** [comment]
Thanks for the report! I'm still not sure what causes this only in Firefox
but not other browsers. Suggestions/PRs welcome!

**Comment by dharmveer18** [comment]
I am facing same issue on chrome with 
python 3.8.2
django 3.0.6

**Comment by Shubhang9** [comment]
Hi guys,
I was making a web application and was facing the same issue in windows 10, python 3.7.6, djnago 3.0.8. I tried a lot of stuff and i finally found  a fix.

I was using a form which called a js function onsubmit which in turn sent a REST call which was getting canceled with the '[WinError 10053] An established connection was aborted by the software in your host machine' error in command prompt.

I added the parameter method='post' and used jQuery.ajax in the js function and i added the event.preventDefault() as well in the function as well as some success and fail callbacks. I don't understand why but now i am not getting the error. 

Hope this help anyone using js along with HTML forms until a the issue is root-caused and fixed. @gwasser maybe it will help you understand the problem.

**Comment by gwasser** [comment]
Thank you @Shubhang9 for the report! I believe this might help in tracking down the error, will need to look at all of our javascript to see if any form submits are missing the `method='post'` parameter and see if that helps.

**Comment by Shubhang9** [comment]
Hello again,
I was stuck in another such scenario as mentioned above(https://github.com/django-helpdesk/django-helpdesk/issues/621#issuecomment-667536408). I guess it is the event.preventDefault() that helped me out because before i added that to my js function, I was still getting the error mentioned in the aforementioned comment. Hope that helps @gwasser.

**Comment by gracebcorrea** [comment]
Hi all , I am with the same error, I use Win10, Django3.1, python-3.8.5-amd64, but in my case it is not just in console.
After I run a function with a fetch with method: 'POST' it executes the post , than happens the error:


_Exception happened during processing of request from ('127.0.0.1', 53981)
Traceback (most recent call last):
  File "C:\Python38\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Python38\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Python38\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\Python38\lib\site-packages\django\core\servers\basehttp.py", line 174, in handle
    self.handle_one_request()
  File "C:\Python38\lib\site-packages\django\core\servers\basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "C:\Python38\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
ConnectionAbortedError: [WinError 10053] Uma conexão estabelecida foi anulada pelo software no computador host

After the "POST" i need to redirect the page but it doesn´t work because of the aborted connectio, any clue?

**Comment by suryarajput274** [comment]
Error:: An established connection was aborted by the software in your host machine
Windows:: 10
python:: 2.7.18
Django:: 1.11.12
Hi, i was facing issue in 29 August 2020, then i had checked:: virtual environment activate , after that clear cache memory from browser.Now it is working properly, it happens when we try to connect a server or accessing data through some instructions.

**Comment by cehceh** [comment]
> Interesting, only get an error in Firefox? I have no idea what would make this browser dependent.
I'm working on Opera and getting the same problem ...
Anaconda environment
Python : 3.8.5
win : 8.1
Django : 2.2.13

`----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 56013)
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\clinicenv\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "D:\ProgramData\Anaconda3\envs\clinicenv\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "D:\ProgramData\Anaconda3\envs\clinicenv\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "D:\ProgramData\Anaconda3\envs\clinicenv\lib\site-packages\django\core\servers\basehttp.py", line 171,
in handle
    self.handle_one_request()
  File "D:\ProgramData\Anaconda3\envs\clinicenv\lib\site-packages\django\core\servers\basehttp.py", line 179,
in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "D:\ProgramData\Anaconda3\envs\clinicenv\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host ma
chine
----------------------------------------
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 55994)
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 56004)
Exception happened during processing of request from ('127.0.0.1', 56001)
Traceback (most recent call last):
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\clinicenv\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "D:\ProgramData\Anaconda3\envs\clinicenv\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "D:\ProgramData\Anaconda3\envs\clinicenv\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "D:\ProgramData\Anaconda3\envs\clinicenv\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\clinicenv\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "D:\ProgramData\Anaconda3\envs\clinicenv\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "D:\ProgramData\Anaconda3\envs\clinicenv\lib\site-packages\django\core\servers\basehttp.py", line 171,
in handle
    self.handle_one_request()
[22/Sep/2020 22:14:21] "GET /clinic/create/patient/ HTTP/1.1" 200 29141
----------------------------------------
  File "D:\ProgramData\Anaconda3\envs\clinicenv\lib\site-packages\django\core\servers\basehttp.py", line 179,
in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
Exception happened during processing of request from ('127.0.0.1', 56003)
  File "D:\ProgramData\Anaconda3\envs\clinicenv\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host ma
chine
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\clinicenv\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "D:\ProgramData\Anaconda3\envs\clinicenv\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
----------------------------------------
  File "D:\ProgramData\Anaconda3\envs\clinicenv\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "D:\ProgramData\Anaconda3\envs\clinicenv\lib\site-packages\django\core\servers\basehttp.py", line 171,
in handle
    self.handle_one_request()
  File "D:\ProgramData\Anaconda3\envs\clinicenv\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "D:\ProgramData\Anaconda3\envs\clinicenv\lib\site-packages\django\core\servers\basehttp.py", line 179,
in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "D:\ProgramData\Anaconda3\envs\clinicenv\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "D:\ProgramData\Anaconda3\envs\clinicenv\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "D:\ProgramData\Anaconda3\envs\clinicenv\lib\site-packages\django\core\servers\basehttp.py", line 171,
in handle
    self.handle_one_request()
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host ma
chine
  File "D:\ProgramData\Anaconda3\envs\clinicenv\lib\site-packages\django\core\servers\basehttp.py", line 179,
in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
----------------------------------------
  File "D:\ProgramData\Anaconda3\envs\clinicenv\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "D:\ProgramData\Anaconda3\envs\clinicenv\lib\socketserver.py", line 720, in __init__
    self.handle()
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host ma
chine
  File "D:\ProgramData\Anaconda3\envs\clinicenv\lib\site-packages\django\core\servers\basehttp.py", line 171,
in handle
    self.handle_one_request()
----------------------------------------
  File "D:\ProgramData\Anaconda3\envs\clinicenv\lib\site-packages\django\core\servers\basehttp.py", line 179,
in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "D:\ProgramData\Anaconda3\envs\clinicenv\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host ma
chine
----------------------------------------`

**Comment by DAnh2012** [comment]
I'm working with conda and it also got fixed after I reopen the conda prompt

**Comment by marvin-kolja** [comment]
I get a similar issue with:
```
Django: 3.1.2
Python: 3.8.6
Win10 build: 18362.1082
```
I don't think it is a problem of the [django-rest-framework](https://www.django-rest-framework.org/) (v.3.12.1) I'm using, however, the exception araises when I try to access any `POST` endpoint with a `GET` request. 

```
# View in Django - http://127.0.0.1/api/task

@api_view(['POST'])
def taskCreate(request):
    serializer = TaskSerializer(data=request.data)

    if serializer.is_valid(raise_exception=True):
        serializer.save()
    return Response(serializer.data)
```

If I try to **access this now with a `GET` request** by simply typing the above URI in the browser I get the following exception:

```
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 62477)
Traceback (most recent call last):
  File "C:\Users\marvi\AppData\Local\Programs\Python\Python38\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\marvi\AppData\Local\Programs\Python\Python38\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\marvi\AppData\Local\Programs\Python\Python38\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\Users\marvi\Documents\Git\nul-backend\env\lib\site-packages\django\core\servers\basehttp.py", line 174, in handle
    self.handle_one_request()
  File "C:\Users\marvi\Documents\Git\nul-backend\env\lib\site-packages\django\core\servers\basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "C:\Users\marvi\AppData\Local\Programs\Python\Python38\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
ConnectionAbortedError: [WinError 10053] Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen
----------------------------------------
Method Not Allowed: /api/task/
[15/Oct/2020 15:40:33] "GET /api/task/ HTTP/1.1" 405 5700
```

Sure, **the `GET` method must not be allowed**, but this **doesn't justify** the `ConnectionAbortedError: [WinError 10053]`

_If I find a solution for it I will post it below._

**Comment by marvin-kolja** [comment]
> 
> 
> Error:: An established connection was aborted by the software in your host machine
> Windows:: 10
> python:: 2.7.18
> Django:: 1.11.12
> Hi, i was facing issue in 29 August 2020, then i had checked:: virtual environment activate , after that clear cache memory from browser.Now it is working properly, it happens when we try to connect a server or accessing data through some instructions.

Cleaning the cache of the browser solves it temporary, yes...But it doesn't solve the inital issue. Thus, it could reoccur?!

**Comment by Wissperwind** [comment]
I have the same error message with Python 3.9 and firefox.

**Comment by chymdyugah** [comment]
I have the same issue. Connection aborted error.
Everything working fine, except for this console level error appearing every now and then.

**Comment by ToBeADevOps** [comment]
python=3.9.0
django=3.1.2

When I pass the parameter using JsonResponse in views.py, if the creat_user method of the auth module was previously used to create the user, An error will be reported :

```
ConnectionAbortedError: [WinError 10053] An Established Connection was aborted by the software in your host machine
```

Everything went back to normal after I skipped the user creation step and passed the parameters. 

Is this my problem or is it a tool problem?

**Comment by da0lli** [comment]
Had the same error and found a solution: Open the chrome dev tools, then rightclick the refresh page button and select "Hard Reload". Hope it helps!

**Comment by Isha307** [comment]
I was trying to play an audio and got this error.

Exception happened during processing of request from ('127.0.0.1', 51084)
Traceback (most recent call last):
  File "c:\python\python37\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "c:\python\python37\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "c:\python\python37\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\Users\MUNA PRASAD\.virtualenvs\DJ-qI2Tt3md\lib\site-packages\django\core\servers\basehttp.py", line 174, in handle
    self.handle_one_request()
  File "C:\Users\MUNA PRASAD\.virtualenvs\DJ-qI2Tt3md\lib\site-packages\django\core\servers\basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "c:\python\python37\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
